language: node_js
node_js:
  - "10"
before_script:
  - npm run test
script:
  - rm -r docs
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: test-auto-deploy
