language: node_js
node_js:
  - "10"
before_script:
  - npm run test
script:
  # TODO: Want to run it at the time of branch=master
  - npm run deploy
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
