name: Run Tests
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-20.04
    name: Run tests
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.16.0'
      - run: npm ci
      - run: npm run test
