name: Run Tests
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-20.04
    name: Run tests
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: npm ci
      - run: npm run test
